version: '3.4'

services:
    campushub_db:
        container_name: postgres_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: Passw0rd
            POSTGRES_DB: CampusHubDB
        ports:
            - "45432:5432"
        networks:
            - shared_campushub_net
        volumes:      
            - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

    #campushub_rabbitmq:
    #    ports:
    #      - "5672:5672"
    #      - "5673:5673"
    #      - "15672:15672" 
    #    networks:
    #      - shared_campushub_net
    #    volumes:      
    #      - ./rabbitmq:/var/lib/rabbitmq
        
    
    campushub_api:
        ports:
          - "10000:80"
        networks:
          - shared_campushub_net
        env_file:
          - env.api
    
    # campushub_identity:
    #    ports:
    #      - "10001:8080"
    #    networks:
    #      - shared_campushub_net
    #    env_file:
    #      - env.identity
    
    #campushub_worker_1:
    #    networks:
    #      - shared_campushub_net
    #    ports:
    #      - "10002:8080"
    #    env_file:
    #      - env.worker
    
    #campushub_worker_2:
    #    networks:
    #      - shared_campushub_net
    #    ports:
    #      - "10003:8080"
    #    env_file:
    #      - env.worker
    
    
networks:
  shared_campushub_net:
    name: campus_hub
    driver: bridge